# Generated by Django 3.2.4 on 2021-07-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcua_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='temp_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
