# Generated by Django 3.2.4 on 2021-07-08 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opcua_app', '0003_pressure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_type', models.CharField(choices=[('t', 'Temperature'), ('p', 'Pressure')], max_length=20)),
                ('pres_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcua_app.pressure')),
                ('temp_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcua_app.temperature')),
            ],
        ),
    ]
