# Generated by Django 3.2.4 on 2021-07-08 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opcua_app', '0004_anomaly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='pres_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opcua_app.pressure'),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='temp_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opcua_app.temperature'),
        ),
    ]
