# Generated by Django 3.2.4 on 2021-07-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcua_app', '0005_auto_20210708_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pressure',
            old_name='pres_timestamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='temp_timestamp',
            new_name='timestamp',
        ),
    ]
